name: boccia_coaching_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  flutter_svg: ^2.0.9
  http: ^1.1.0
  shared_preferences: ^2.2.2
  pdf: ^3.10.7
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/isologo-vertical.png
    - assets/images/isologo-vertical-1tinta.png
    - assets/images/isologo-horizontal.png
    - assets/images/icon-iso.png
    - assets/images/google-logo.svg
    - assets/data/test.force.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app-icon-1024.png"
  adaptive_icon_background: "#1d3557"
  adaptive_icon_foreground: "assets/images/app-icon-1024.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/app-icon-1024.png"
  macos:
    generate: true
    image_path: "assets/images/app-icon-1024.png"
